### ISSUE TITLE
调度状态有问题

### ISSUE THREAD

**Issue by chengfan2017** [mouday/SpiderAdmin#2]
![image](https://user-images.githubusercontent.com/19389193/64102792-40adb500-cda3-11e9-8aae-b9415eb375b5.png)

**Comment by chengfan2017** [comment]
周期的显示正常 定时有问题

**Comment by mouday** [comment]
是不执行吗？

**Comment by chengfan2017** [comment]
有时候定时任务刚创建的时候调度状态直接是失败的，取消再重新创建几次又恢复正常

**Comment by mouday** [comment]
> 有时候定时任务刚创建的时候调度状态直接是失败的，取消再重新创建几次又恢复正常

对，没执行过的状态都是红色的，执行过就变绿色了
