### ISSUE TITLE
爬虫定时调度选择（单次调度）出现多次调度

### ISSUE THREAD

**Issue by 1414044032** [mouday/SpiderAdmin#3]
### version
**0.0.31**

### OS/Browsers version
**window 10 /Chrome**

### Steps to reproduce
**通过scrapyd-deploy 将爬虫部署后，点击爬虫项目==》master==》项目列表下选择（查看项目中的爬虫）==》点击设置定时==》设置单次任务（选择一个未来的时间）==》提交表单，提示添加成功**

### What is Expected?
**在设置的时间点开始调度爬虫任务，并且不再执行**

### What is actually happening?
**在设置的时间点开始调度爬虫任务，但是在一次调度后会再次调度爬虫任务，直到超过当前时间 分内（比如设置 2020-05-07 17:10:30 爬虫将会在2020-05-07 17:10:30 开始执行，并且完成后再次执行，直到当前时间超过 2020-05-07 17:10 ）**
### 其他数据
（单次调度出现的多条调度记录 ==》拷贝自log_spider表）
1	baidu	69	3	0	2020-05-07 17:31:24
2	baidu	69	1	0	2020-05-07 17:31:26
3	baidu	69	0	0	2020-05-07 17:31:31
4	baidu	69	0	0	2020-05-07 17:31:36
5	baidu	69	0	0	2020-05-07 17:31:41
6	baidu	69	0	0	2020-05-07 17:31:46
7	baidu	69	0	0	2020-05-07 17:31:51
8	baidu	69	0	0	2020-05-07 17:31:56

**Comment by mouday** [comment]
问题已修复，可以更新到版本 0.0.32
`pip3 install -U spideradmin`
