### ISSUE TITLE
部署篇写得太简单了

### ISSUE THREAD

**Issue by yuanrenkai** [mouday/SpiderAdmin#5]
1.  关于 端口 和 访问主机配置 可增加 ，表示要不是搞过开发，就只能本机（127.0.0.1:5000）访问么？？
2.  增加静默启动

注： 我之前没用过python ,不知道对不对啊，包涵

**Comment by mouday** [comment]
可能没有考虑到部分同学，可以在初始化后目录下修改配置文件,
```
# 修改主机地址，设置为外网访问
HOST = 0.0.0.0

# 配置端口号
PORT = 8080
```
